services:
  vitepress:
    container_name: practice-vitepress
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    command: >
      sh
    tty: true
